#ifndef ERROR_H
#define ERROR_H

#define SUCCESS 0
#define GENERIC_ERROR 1

#define MEMORY_ERROR 2
#define DATA_INTEGRITY_ERROR 3
#define INVALID_PACKET_ERROR 4
#define FILE_ERROR 5
#define INVALID_ARGUMENTS 6
#define RANGE_ERROR 7
#define NO_DATA_ERROR 8

#endif // ERROR_H
