#pragma once


#define REFERENCE_BOARD_EMPTY_FIELD -1
#define BOARD_SIDE_LENGTH 10
#define ACTIVE_BOARD_SIDE_LENGTH 8
#define BOARD_SIZE BOARD_SIDE_LENGTH * BOARD_SIDE_LENGTH
#define ACTIVE_BOARD_SIZE ACTIVE_BOARD_SIDE_LENGTH * ACTIVE_BOARD_SIDE_LENGTH
#define REF_MAX_FIELD_INDEX 32

enum Player {
  BLACK_PLAYER = 0,
  WHITE_PLAYER = 1
};

enum ReferenceBoardField {
  REF_OUTSIDE_FIELD = -2,
  REF_WHITE_FIELD = -1
};


enum BoardField {
  BLACK_PIECE = 51,
  WHITE_PIECE = 52,
  BLACK_KING = 53,
  WHITE_KING = 54,
  EMPTY_FIELD = 55,
  INVALID_FIELD = 56,
  OUTSIDE_FIELD = 57
};



typedef int Board[BOARD_SIDE_LENGTH][BOARD_SIDE_LENGTH];
